### ISSUE TITLE
Tray icons position and order

### ISSUE THREAD

**Issue by hmlendea** [pixel-saver/pixel-saver#104]
Is there a way to move the tray icons on the right, near the AppMenu?
And also have them displayed all the time, for any kind of application, even those that are not maximized (for consistency reasons).

Having them on the right is really ugly IMO and is the only reason why I don't use this.
It would be really cool to have an options window to customize this. Also maybe the order of the buttons (Because it would look better if they were mirrored when they are on the left, like they are on Ubuntu's Unity)

**Comment by alexeymuranov** [comment]
You meant the minimise-normalise-close buttons, and you meant on the *left*, right?

**Comment by alexeymuranov** [comment]
I would also like to be able to move the minimise-normalise-close buttons to the left of the panel, because i do not have any more space on the right because of too many panel applets on the right.

**Comment by HoratiuMl** [comment]
Yeap, that's what I meant.

I also kinda dislike that the AppMenu or whatever it's called (the application icon on the top panel) is showing the active window's title instead of the application's name. I think this takes way too much space and that the app's name is more helpful. An option for toggling this feature would be welcome.

Also, when the minimise, normalise and close buttons are put on the left, then the appMenu will _have_ to remain as is in default (app name, not window title) because there wouldn't be enough space otherwise.

**Comment by alexeymuranov** [comment]
About the order of the buttons, IMO it would be strange and confusing to have them in different order in "pixelsaved" maxmised windows than everywhere else.  For me, it would be perfect to be able to just "bind" them with the application icon-title in the usual position: if the current theme has window buttons in the right left corner, then to gave them just to the right of the "AppMenu".

**Comment by pcercuei** [comment]
If there's an option to change the position of the buttons, I'd also like an option to hide them. On my tablet, those are too small to click anyway.

**Comment by HoratiuMl** [comment]
@pcercuei you could make the panel bigger, I think that will make those buttons bigger as well (they should, if they scale to the panel size). It is done with a simple and short CSS file that you can find on the net if you decide to do it.

An option to hide them could be useful for some people. When using a table, for example, I think that the AppMenu is more convenient to use than on desktop, and it already has window controls included.

**Comment by brianc118** [comment]
See [here](http://askubuntu.com/questions/9867/how-to-switch-window-controls-to-the-left-gnome-shell) to move buttons to left. Also use [this](https://extensions.gnome.org/extension/810/hide-app-icon/) to hide the app button.

**Comment by alexeymuranov** [comment]
@brianc118, thanks for the links, i moved my window title bar buttons to the left with
```shell
dconf write /org/gnome/desktop/wm/preferences/button-layout "'close,minimize,maximize:appmenu'"
```

However, for this extension, i would have liked to have an option to keep those buttons next to the window title.  It is a bit weird when they pop up in the left corner and move my Application menu.

**Comment by brianc118** [comment]
I got read of the application menu altogether and disabled the hot corner with another extension.

**Comment by tallero** [comment]
>Is there a way to move the tray icons on the right, near the AppMenu?

If I am correct, someone wrote a patch but it was rejected, don't remember why.

>And also have them displayed all the time, for any kind of application, even those that are not maximized (for consistency reasons).

That would result in redundancy, so there would be no pixel saving and we should need to change the name.

>I also kinda dislike that the AppMenu or whatever it's called (the application icon on the top panel) is showing the active window's title instead of the application's name. I think this takes way too much space and that the app's name is more helpful. An option for toggling this feature would be welcome.

Actually in GNOME 3.32 title displaying is not correctly working except when alt-tabbing, so you got this in a way or another.

**Comment by hmlendea** [comment]
:) I didn't expect a new reply after all this time.

I'm not using this exception anymore since I've switched to a higher resolution display.

But thanks anyway.

Btw from my point of view, this issue can be closed, unless others still think it's relevant.

**Comment by tallero** [comment]
>:) I didn't expect a new reply after all this time.

If the software keeps working, it is mantainable, and people contribute to it has meaning to do keep replying! :D
