### ISSUE TITLE
Bug in the Vertex theme

### ISSUE THREAD

**Issue by antmak** [pixel-saver/pixel-saver#125]
I've tried the vertex theme. I see the horizontal gap instead of the window title. See 
![screenshot from 2017-04-27 15-29-32](https://cloud.githubusercontent.com/assets/675314/25472697/0ec7d98c-2b5f-11e7-954a-44514516283a.png)
screenshot. Have you any ideas how to fix it? I use gnome 3.14 and pixel-saver with minor patches.  Please tell me with a place in the code that can be fixed. Thx

**Comment by tallero** [comment]
Does this still affect you?

**Comment by antmak** [comment]
No because I switched to KDE :)
