### ISSUE TITLE
Wrong order when using global menu extension

### ISSUE THREAD

**Issue by vmavromatis** [pixel-saver/pixel-saver#129]
Hi, thank you for the extension. I'm trying to use it together with Global menu extension (https://github.com/lestcape/Gnome-Global-AppMenu) but I get this problem

![problem](http://i.imgur.com/exAXsQQ.png)

How can I place the icons to the far left?? Ideally I would want the to override the "Terminal" text. Thank you!

**Comment by tallero** [comment]
Search for `button-layout` with the dconf-editor and try putting in this value:

    appmenu:minimize,maximize,close
