### ISSUE TITLE
Title Bar not hidden, buttons still in top panel

### ISSUE THREAD

**Issue by StephenFalcone** [pixel-saver/pixel-saver#145]
Title bar is not hidden. Buttons still show up in the top panel. Tried installing and uninstalling multiple times, doesn't seem to help. Also disabled every other extension. For all programs, not just firefox. Am I installing incorrectly, or is there something else I can do to fix this?

![screenshot from 2017-10-04 18-42-25](https://user-images.githubusercontent.com/8637395/31203159-d2c0bb7c-a933-11e7-9e87-73491ea1d86e.png)

**Comment by daudo** [comment]
confirming this, happens on the latest and greatest manjaro/arch linux running gnome 3.26.2

**Comment by daudo** [comment]
fixed the "issue" by installing xprop and xwininfo, working flawless now!

**Comment by gmpreussner** [comment]
@daudo didn't work for me on ArchLinux with Gnome 3.26.2. Did you do anything else besides installing the two packages?

**Comment by daudo** [comment]
works for me on the latest Manjaro release with gnome 3.26.2, so it has to work with your ArchLinux, too.

All I had to do was to additionally install xprop and xwininfo, that was it.

**Comment by tallero** [comment]
This is the proof we need #148.
