### ISSUE TITLE
Handle missing dependencies

### ISSUE THREAD

**Issue by amirkarimi** [pixel-saver/pixel-saver#148]
After updating my Manjaro Linux, pixel-saver stopped working (Error loading extension). Not sure what caused the issue as lots of packages are updated. 

Error (got from `journalctl /usr/bin/gnome-shell`):
```
Extension "pixel-saver@deadalnix.me" had error: GLib.SpawnError: Failed to execute child process “xprop” (No such file or directory)
```

Gnome: 3.24.2

**Comment by mishugashu** [comment]
I had this problem on ArchLinux with a fresh install (gnome 3.26.1). Installing [xorg-xprop](https://www.archlinux.org/packages/extra/x86_64/xorg-xprop/) fixed it.

**Comment by amirkarimi** [comment]
@mishugashu :+1: Installing `xorg-xprop` worked for me as well. I'm not sure if I should close this issue or is it possible to do something about it; like better error handling or requiring the user to install the dependency.
