### ISSUE TITLE
app_menu.js error

### ISSUE THREAD

**Issue by elieobeid7** [pixel-saver/pixel-saver#152]
```
Source ID 14529 was not found when attempting to remove it
Attempting to remove actor of type 'StLabel' from group of class 'ShellGenericContainer', but the container is not the actor's parent.
JS ERROR: TypeError: label is undefined
onAppMenuHover/tooltipDelayCallbackID<@/home/user/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/app_menu.js:116:8

```

**Comment by tallero** [comment]
Can you confirm this happens on recent versions, too?

**Comment by elieobeid7** [comment]
I can't, it only works on gnome, I opened it a year ago, now I'm dual-booted between windows 10 and ubuntu 16.04 unity.

If you can't reproduce it then please close it because I won't be able to test this until I switch to gnome someday.

**Comment by tallero** [comment]
I am sorry. I sincerely hope you will come back on GNOME soon lol.
