### ISSUE TITLE
Windows control buttons disappear when switch between windows (Alt-Tab)

### ISSUE THREAD

**Issue by KSXGitHub** [pixel-saver/pixel-saver#162]
### Steps to reprocedure

* **Step 1:** Open 2 windows, one uses classic window (e.g. GNOME terminal), one doesn't (e.g. Nautilus).

* **Step 2:** Open Activity Overview (press <kbd>Super</kbd> or move mouse to top-left corner), choose classic window, you should see window control buttons in top bar as expected.

* **Step 3:** Open Activity Overview again, choose non-classic window, you should see window control buttons disappear from top bar as expected.

* **Step 4:** Use <kbd>Super + Tab</kbd> or <kbd>Alt + Tab</kbd> to switch from non-classic window to classic window. This time however, **window control buttons won't appear** (You need to choose the window from Activitive Overview for it to appear).

**Comment by tallero** [comment]
Buttons are always visible in the bar even when the non-classic window is focused.
