### ISSUE TITLE
Very intense CPU usage on opening popup menus

### ISSUE THREAD

**Issue by alkismavridis** [pixel-saver/pixel-saver#165]
When I have pixel-saver enabled, I face performance issues when I open popup menus.
My mouse pointer moves "in frames", in a very unresponsive way, and my cpu usage goes crazy for a short period of time. If I hover over different menus (like we typically do in a menu bar) the problem becomes more intense.

This happens in all popup menus (for example: typical right click, menu bar on the top of a program, dropdowns, like color choosers in Libre office, etc).

Deactivating the plugin makes the problem disappear.
Also it is interesting to notice that this does not happen with intellij menus (I guess because they use other GUI engine).

I run Ubuntu 17.10 with its default Gnome (problem appears in both xorg and wayland).
My hardware is an Asus yoga, Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 
and 16Gb ram.

**Comment by phadej** [comment]
I experience this too. E.g. context menus in terminal, annoying

**Comment by dmfs** [comment]
Same problem under Fedora (27 and 28) running Wayland. Though, I've only noticed it under Libreoffice so far. Disabling pixel-saver fixes the issue.

**Comment by tallero** [comment]
I see this happens independently of pixel saver. Can someone confirm that this happens because of the extension?

**Comment by phadej** [comment]
@tallero when I disabled the extension, pop menus become instantaneous.

**Comment by tallero** [comment]
@phadej can i close this? (are you using the latest version?)

**Comment by K-gihu** [comment]
Save problem occured on Gnome 42.1, archlinux Kernel: 5.17.5-arch1-1. I installed the lastest AUR version of pixel-saver 1.28-1.

Enabling pixel-saver caused opening context menu and opening new window to be laggy, it is more laggy on my second monitor. 

Disabling pixel-saver make it normal.
