### ISSUE TITLE
Stops working after a wile.

### ISSUE THREAD

**Issue by tiotrom** [pixel-saver/pixel-saver#170]
Ubuntu 18.04. After a couple of hours newly opened apps/windows do not work anymore. Old opened ones still work. Only way to fix it is to go to gnome extensions website - Installed Extensions - Disable and remove Pixel Saver and install again. It is annoying to be honest, but I love it so much I can't remove it :D - are you aware of this bug?

**Comment by updeshxp** [comment]
I can confirm this, Ubuntu 18.04

**Comment by tallero** [comment]
Is this still happening with a recent version?
