### ISSUE TITLE
Update GNOME extensions website's zip

### ISSUE THREAD

**Issue by Jomik** [pixel-saver/pixel-saver#177]
"I see that #174 was merged. Can you publish it to GNOME extensions?"

![pending reviews](https://user-images.githubusercontent.com/7817636/70866178-c1657b00-1f66-11ea-996f-c06ad682c01f.png)

Anyone can help approve the patches [here](https://extensions.gnome.org/review/).
Until published,

| Gnome Shell | Latest recommended version (github)                                          |
|-------------|----------------------------------------------------------------------|
| 3.12        | [1.3](https://github.com/deadalnix/pixel-saver/releases/tag/1.3)     |
| 3.14        | [1.5.1](https://github.com/deadalnix/pixel-saver/releases/tag/1.5.1) |
| 3.15        | [1.10](https://github.com/deadalnix/pixel-saver/releases/tag/1.10)   |
| 3.24        | [1.12](https://github.com/deadalnix/pixel-saver/releases/tag/1.12)   |
| 3.26        | [1.14](https://github.com/deadalnix/pixel-saver/releases/tag/1.14)   |
| 3.30        | [1.18](https://github.com/deadalnix/pixel-saver/releases/tag/1.18)   |
| 3.32        | [1.20](https://github.com/deadalnix/pixel-saver/releases/tag/1.20)   |
| 3.34        | [master](https://github.com/deadalnix/pixel-saver)                   |

**Comment by sethwoodworth** [comment]
It would also be great to increment your tagged version and release it here on github.  The README shows how to install the version of the project from 2016.

**Comment by skewty** [comment]
Will this still show the title when the app menu is removed in the next gnome release?

**Comment by xim** [comment]
Any reason why this isn't released yet?

**Comment by seraphyn** [comment]
@xim Good question.
Still waiting, too

**Comment by FedgeNo** [comment]
Just upgraded to Fedora 29 and now I'm stuck with title bars. Installation instructions on here didn't make any difference.

**Comment by andrewfader** [comment]
+1

**Comment by tallero** [comment]
@Jomik @sethwoodworth @skewty @xim @seraphyn @FedgeNo @highvoltage @andrewfader @Baksalyar 
We are waiting for someone to read this:
https://mail.gnome.org/archives/gnome-shell-extensions-list/2019-August/msg00000.html

**Comment by tallero** [comment]
Upgraded extension on the website.
