### ISSUE TITLE
Icons of Yaru theme not used

### ISSUE THREAD

**Issue by keunes** [pixel-saver/pixel-saver#184]
Related to #132, also icons for the new community-made Yaru theme aren't supported by Pixel Saver. I really love both Yaru and Pixel Save (thank you @deadalnix for creating it), and would love them to work together.

Following my request to the Yaru developers, they were super fast to create a PR to add Yaru support to Pixel Saver in #183. It would be awesome if that PR could be added.

**Comment by tallero** [comment]
@keunes merged.

**Comment by keunes** [comment]
Great, thanks!
