### ISSUE TITLE
Doesn't work on gnome-shell 3.30.1

### ISSUE THREAD

**Issue by mahdiG** [pixel-saver/pixel-saver#185]
I installed the extension from both extensions.gnome.org and from github. Neither of them work.

**Comment by seraphyn** [comment]
As I remember:
```
git clone https://github.com/deadalnix/pixel-saver.git
cd pixel-saver/
git checkout 1.10
cp -r pixel-saver@deadalnix.me -t ~/.local/share/gnome-shell/extensions
gnome-shell-extension-tool -e pixel-saver@deadalnix.me
```
Restart Shell

**Comment by mahdiG** [comment]
I followed the above instruction and it still doesn't work and shows error when in gnome tweak tools.

**Comment by seraphyn** [comment]
What type of error?
As I remember, it should’ve worked 

Does somebody have a fix for this?
I’m on the walk and do not have a laptop by my side, sorry 


BTW when do we got anothe milestone for installation under the new shell ?

**Comment by randomCards** [comment]
It is still necessary (replace a sting in 2 file and restart the shell): 
https://github.com/deadalnix/pixel-saver/issues/178#issuecomment-423320666
reinstall if didnt work
:(

**Comment by mahdiG** [comment]
I changed those two lines as mentioned and it worked. Thanks.

**Comment by mwcz** [comment]
Thank you @randomCards, works great now.

**Comment by JensTimmerman** [comment]
@seraphyn I made a working fork at https://github.com/JensTimmerman/pixel-saver
Also uploaded it to gnome-extensions, waiting for review.

**Comment by gbraad** [comment]
@JensTimmerman why did you not push a PR here?

**Comment by gbraad** [comment]
See: #189

**Comment by saifjsl** [comment]
Hi, any news on this? why does the author does not fix this

**Comment by seraphyn** [comment]
@gbraad For sure, but when he's not taking part in the conversation, doe not implement fixes and the last work was 7 months ago, how long should we wait and when should we go on?

@deadalnix it would be great if you could take part here.

**Comment by saifjsl** [comment]
JensTimmerman repo doesnt work for me either, like the extension doesnt show up on extensions list, even after I enable it (Gnome 3.30.2).

The one here works with changing that variable name

**Comment by saifjsl** [comment]
Also, this plugin breaks "Window list" extension, by removing their texts

**Comment by JensTimmerman** [comment]
@gbraad I did not make any changes myself, I just merged pr's that were open on this fork into my fork, and now it works for me... There is no PR I can make, they are all already there...

As for why the author does not fix this, I think this is a matter of the gnome extensions team not reviewing/approving the extension. Afaik deadalnix is doing all the right things, but the gnome extensions website team is not responsive?
It's not my goal to fork this project, I just wanted a version with some fixes in it to install locally...

**Comment by JensTimmerman** [comment]
https://extensions.gnome.org/extension/1638/pixel-saver-fork/ was reviewed by gnome and is up on the website now.

**Comment by seraphyn** [comment]
@JensTimmerman Great thanks

**Comment by mwcz** [comment]
Thank you @JensTimmerman !

**Comment by gbraad** [comment]
@JensTimmerman it seems the extenions team has several issues. I have seen many extensions in recent time publishing on GitHub or other means, with a description on how to activate (clone and link) to activate extensions. It seems therefore to be a general issue. Thanks for combining the fixes... but is there something we can do to help with this?

**Comment by JensTimmerman** [comment]
@gbraad testing pr's and merging them in my fork and pushing to gnome is no work at all, but I don't have any experience with writing an extension myself, so you can help by looking into https://github.com/deadalnix/pixel-saver/pull/191 and help improve that pr? Then I can merge and push that one too ;)

**Comment by lvtanxi** [comment]
@seraphyn Can you post the document? I met this problem, too.

**Comment by tallero** [comment]
@gbraad the thing about the installation (at least on my extensions) is because of clarity, also because this way people

1) get to know how extension work
2) not everyone has the browser extension installed

GNOME extensions website works well, problems usually arise when mantainers abandon the extensions (obviously this is not the case); the policy says they need to have original mantainer to explicitly authorize other people to take over.
