### ISSUE TITLE
Buttons layout do not show in maximised state.

### ISSUE THREAD

**Issue by sumanta23** [pixel-saver/pixel-saver#186]
gnome-shell:  3.30.3 
Well the code is dependent on ":" at the end in case the wm preference. in some case the ":" field might no be available.
@icollar @deadalnix probably there should be another condition added(length check) based on the previous commit.
`
if (order.indexOf(':') == -1 && order.length===1)
`

https://github.com/deadalnix/pixel-saver/blob/42347431dd881947c738593b7c1861f1b1b6c9c8/pixel-saver%40deadalnix.me/buttons.js#L48

**Comment by tallero** [comment]
@sumanta23 merged.
