### ISSUE TITLE
Guake terminal toggle delay when pixel-saver in use

### ISSUE THREAD

**Issue by jimouris** [pixel-saver/pixel-saver#190]
Hi, first of all great work, pixel-saver is a must have app for gnome.

I observed that when I toggle the visibility of [guake-terminal](http://guake-project.org/) and have the pixel-saver extension enabled, guake has a delay before opening. I don't know how pixel-saver affects guake however it is pretty annoying.

**Comment by AndrewDant** [comment]
Could you give more details on how to replicate this problem? I'm running Gnome on Ubuntu 16.04 with pixel saver and a number of other extensions and Guake toggles instantly.

**Comment by jimouris** [comment]
I do not know if this problem still exists, I am on 19.04 now. At the time, I eventually disabled pixel-saver and used a similar extension.
