### ISSUE TITLE
Request to use _MOTIF_WM_HINTS since _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED is removed

### ISSUE THREAD

**Issue by shemgp** [pixel-saver/pixel-saver#193]
Hello,

In GNOME 3.32 _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED is gone: https://gitlab.gnome.org/GNOME/mutter/merge_requests/221

They say that extensions should use _MOTIF_WM_HINTS instead.

Could you update this nice extension to use that instead?

Thank you.

**Comment by tallero** [comment]
This has been merged in #199.
