### ISSUE TITLE
pixel-saver and muti-monitors-add-on error when locking

### ISSUE THREAD

**Issue by clausavram** [pixel-saver/pixel-saver#194]
I've enabled both **pixel-saver** and **multi-monitors-add-on** and when locking gnome (Super+L), the lock screen does not appear, but the screen becomes completely purple. I have to hit Super+L again to see the lock screen and login dialog. After unlocking, gnome's appearance is altered, as if soft-crashing:
- Ubuntu Gnome UI reverts to stock Gnome style
- extensions are disabled (and some others can't be re-enabled due to exceptions from these 2) and can't be re-enabled until the next log-out + re-login

The issue reproduces for me only if both extensions are enabled at the same time.

I've captured a _gnome-shell_ log (`journalctl  /usr/bin/gnome-shell -f`) with exceptions of the error-ed locking:
- 10:47:18 - enable multi-monitors-add-on, then pixel-saver
- 10:47:47 - log out + re-login - otherwise the issue does not reproduce
- 10:49:03 - 1st lock (Super+L) - screen becomes purple
- 10:49:36 - 2nd lock (Super+L) - lock screen appears and I can enter my password to unlock
- 10:50:22 - unlock -> all extensions have been disabled, with some not allowed to re-enable, Gnome UI appearance changed
- 10:50:28 - 3rd lock (Super+L) - confirmed that the issue still occurs -> last logging is the exception again

```
$ apt list | grep -e pixelsaver -e multi-monitors
gnome-shell-extension-multi-monitors/bionic,bionic 0.00~git20171014.1.df5d6e4-1 all
gnome-shell-extension-pixelsaver/bionic,bionic 1.10+git20161217-49f47bf-1 all


$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

$ uname -a
Linux ubuntu-machine 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

multi-monitors-add-on issue: https://github.com/spin83/multi-monitors-add-on/issues/84

```
[gnome-shell.log.tar.gz](https://github.com/deadalnix/pixel-saver/files/2965614/gnome-shell.log.tar.gz)

**Comment by vthuongt** [comment]
I think this is related to this issue https://github.com/pixel-saver/pixel-saver/issues/196 
Your logs also show some errors due to  some failing deallocation (right before the stack trace begins).

**Comment by richardmodis** [comment]
I have the same issue, each time after unlocking the screen I have to restart my gnome-shell.

**Comment by tallero** [comment]
Are you talking about the GNOME extension website's version or the last from `master`?

**Comment by clausavram** [comment]
I (at least) was using the one from GNOME's website

**Comment by tallero** [comment]
@clausavram the version from extension website is really old and I still can't upload a new version (see #177). If you can, try installing it from github; I am using it and can't reproduce the bug on that version.
