### ISSUE TITLE
Buttons display when maximized

### ISSUE THREAD

**Issue by RossComputerPerson** [pixel-saver/pixel-saver#198]
![Screenshot from 2019-04-09 13-22-27](https://user-images.githubusercontent.com/19699320/55832506-93bc5e00-5aca-11e9-81e0-3780a7f6e24f.png)

**Comment by SpaceboyRoss01** [comment]
Also should include support for firefox's titlebar merged with the tabs

**Comment by SpaceboyRoss01** [comment]
![Screenshot from 2019-04-09 13-26-28](https://user-images.githubusercontent.com/19699320/55832749-134a2d00-5acb-11e9-8fe0-318d4e862107.png)
This extension is buggy as shit sometimes.

**Comment by tallero** [comment]
I remember client-side decorated windows always showing windows control despite their maximized status when using pixel-saver.

Technically, the choice of which controls are to be shown in client-side decorated windows is on the app developer. In any case the window manager can globally override the controls disposition, in fact GNOME shows by default only the close button.

On GNOME (`mutter`), you can hide "minimize" and "maximize" buttons from `gnome-tweaks` itself or change, reorder or even remove all of them by changing the value at

    /org/gnome/desktop/wm/preferences/button-layout

with `''` using `dconf-editor`.

This is needed on GNOME mobile and personally I like it even more on pc:

![Daty](https://gitlab.gnome.org/World/Daty/raw/master/screenshots/editor.png)

**Comment by tallero** [comment]
At the moment is it impossible to hide headerbar buttons without messing with applications at runtime or without making disappear window controls on all gtk windows.
