### ISSUE TITLE
Didn't worked in Ubuntu 19.10.

### ISSUE THREAD

**Issue by PranavBhattarai** [pixel-saver/pixel-saver#204]
![Screenshot from 2019-12-07 07-12-41](https://user-images.githubusercontent.com/32763112/70366672-29f68d00-18c1-11ea-97ba-401e97da0e92.png)

**Comment by tallero** [comment]
It works on my Archlinux with GNOME 3.34.1. You can provide the error on your machine this way:

- Run this in your terminal

    journalctl /usr/bin/gnome-shell -f -o cat

- Restart GNOME Shell (press `alt+F2` and then `r`)

Copy here what you got in the terminal after doing that.

**Comment by PranavBhattarai** [comment]
@tallero 

`pranav@Exam:~$ journalctl /usr/bin/gnome-shell -f -o cat
JS ERROR: TypeError: global.screen is undefined
getWindow@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13
activateWindow@resource:///org/gnome/shell/ui/main.js:608:9
_finish@resource:///org/gnome/shell/ui/altTab.js:614:9
_keyReleaseEvent@resource:///org/gnome/shell/ui/switcherPopup.js:192:17

JS ERROR: TypeError: global.screen is undefined
getWindow@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13
activateWindow@resource:///org/gnome/shell/ui/main.js:608:9
_finish@resource:///org/gnome/shell/ui/altTab.js:614:9
_keyReleaseEvent@resource:///org/gnome/shell/ui/switcherPopup.js:192:17

JS ERROR: TypeError: global.screen is undefined
getWindow@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13

JS ERROR: TypeError: global.screen is undefined
getWindow@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13

JS ERROR: TypeError: global.screen is undefined
getWindow@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13
activateWindow@resource:///org/gnome/shell/ui/main.js:608:9
_finish@resource:///org/gnome/shell/ui/altTab.js:614:9
_keyReleaseEvent@resource:///org/gnome/shell/ui/switcherPopup.js:192:17

JS ERROR: TypeError: global.screen is undefined
getWindow@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13
activateWindow@resource:///org/gnome/shell/ui/main.js:608:9
_finish@resource:///org/gnome/shell/ui/altTab.js:614:9
_keyReleaseEvent@resource:///org/gnome/shell/ui/switcherPopup.js:192:17

JS ERROR: Exception in callback for signal: hidden: TypeError: global.screen is undefined
getWindow@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13
_emit@resource:///org/gnome/gjs/modules/signals.js:135:27
_hideDone@resource:///org/gnome/shell/ui/overview.js:622:9
onComplete@resource:///org/gnome/shell/ui/overview.js:602:31
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:74:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:131:56

JS ERROR: TypeError: global.screen is undefined
getWindow@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13

JS ERROR: TypeError: global.screen is undefined
getWindow@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/pranav/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13

[1]+  Stopped                 journalctl /usr/bin/gnome-shell -f -o cat


`

**Comment by gornostal** [comment]
I have similar errors in PoP OS based of Ubuntu 19.10:
```
JS ERROR: Extension pixel-saver@deadalnix.me: TypeError: global.screen is undefined                                                           
enable@/home/agornostal/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/decoration.js:355:2                                      
enable@/home/agornostal/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/extension.js:60:2                                        
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:132:13                                                                 
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:403:13                                                        
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:400:9
_init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:529:61
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:159:13
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:245:22
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:108:13

JS ERROR: TypeError: global.screen is undefined
getWindow@/home/agornostal/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/util.js:9:1
updateVisibility@/home/agornostal/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:209:13
createButtons/<@/home/agornostal/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js:94:3
```

Is there a fix or a workaround for this issue?

**Comment by tallero** [comment]
Are you guys using the latest `pixel-saver` version (obtainable from GNOME extensions website or from this repository)?

**Comment by PranavBhattarai** [comment]
@tallero 

This extension is installed from the Firefox browser using [this](https://extensions.gnome.org/extension/723/pixel-saver/) URL. Hope this is the one which is official.
The gnome version is 3.34.1. 

The file is empty. Nothing is written in **util.js** because I saw nothing when I did `sudo nano util.js`.

```
pranav@Exam:~/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me$ ls
app_menu.js    extension.js   util.js
buttons.js     metadata.json
decoration.js  themes

```

**Comment by PranavBhattarai** [comment]
@tallero  Reinstalled it. And this inside util.js

```
const Mainloop = imports.mainloop;
const Meta = imports.gi.Meta;

const MAXIMIZED = Meta.MaximizeFlags.BOTH;

function getWindow() {
	// get all window in stacking order.
	let windows = global.display.sort_windows_by_stacking(
		global.screen.get_active_workspace().list_windows().filter(function (w) {
			return w.get_window_type() !== Meta.WindowType.DESKTOP;
		})
	);
	
	let i = windows.length;
	while (i--) {
		let window = windows[i];
		if (window.get_maximized() === MAXIMIZED && !window.minimized) {
			return window;
		}
	}
	
	return null;
}

function onSizeChange(callback) {
	let callbackIDs = [];
	let wm = global.window_manager;
	
	try {
		// Gnome 3.16
		callbackIDs.push(wm.connect('maximize', callback));
		callbackIDs.push(wm.connect('unmaximize', callback));
	} catch (e) {
		// Gnome 3.18+
		callbackIDs.push(wm.connect('size-change', callback));
	}
	
	// Needed for window drag to top panel (this doesn't trigger maximize).
	callbackIDs.push(wm.connect('hide-tile-preview', callback));
	
	// note: 'destroy' needs a delay for .list_windows() report correctly
	callbackIDs.push(wm.connect('destroy', function () {
		Mainloop.idle_add(callback);
	}));
	
	return callbackIDs;
}


```

**Comment by gornostal** [comment]
I also have the same contents of util.js as above

**Comment by gornostal** [comment]
As a workaround you can download [this](https://github.com/pixel-saver/pixel-saver/tree/master/pixel-saver%40deadalnix.me) directory from github and replace existing one in `~/.local/share/gnome-shell/extensions`.
Then after re-login it should work.

**Comment by tallero** [comment]
![gnome extensions](https://user-images.githubusercontent.com/7817636/70866154-721f4a80-1f66-11ea-98c8-782283775988.png)

Latest version was still not present on GNOME extensions (and version compatibility was not properly specified). Now someone has to approve these:

![pending reviews](https://user-images.githubusercontent.com/7817636/70866178-c1657b00-1f66-11ea-996f-c06ad682c01f.png)

You can contribute [here](https://extensions.gnome.org/review/).

**Comment by PranavBhattarai** [comment]
@tallero 
Sorry, but so what do you want in this condition? Install the zip file from downloading repo or wait until it comes in extensions.gnome.com officially? 
(noob)

**Comment by tallero** [comment]
@PranavBhattarai If you want to use the extension you have now to install the zip from the repo, I have no control over GNOME extensions reviews and I can't give estimations on approvals. 

When the website will be updated, the usual infrastructure will advice you to upgrade as if no manual installation happened.
