### ISSUE TITLE
Application Name shifting to right side in GNOME 3.34

### ISSUE THREAD

**Issue by Ayush-Walia** [pixel-saver/pixel-saver#205]
![Screenshot from 2019-12-07 21-54-08](https://user-images.githubusercontent.com/16828403/70377669-f6f1df00-193c-11ea-99b0-d0d71217e55c.png)

After updating to ubuntu 19.10, application name is shifting to right side and getting cut off.
It only happens after installing pixel saver(removed pixel saver and issue was gone).
To get this behaviour, open any application. it will show name correctly, then open any other application, switch back to previous application and this happens.

**Comment by tallero** [comment]
Yes, this is known since merging 3.34 patches. Since Ubuntu is slow in distributing GNOME the bug is being discovered only now. Maybe allocation order in those patch is not optimal or an allocation refresh is needed somewhere.

**Comment by Ayush-Walia** [comment]
hovering with mouse didn't helped but changing window seems to be a workaround.

**Comment by Ayush-Walia** [comment]
Update: Issue got resolved automatically after updating to Ubuntu 20.04
