### ISSUE TITLE
Extension in Error state: No JS module 'tweener'

### ISSUE THREAD

**Issue by ironchicken** [pixel-saver/pixel-saver#214]
I've installed from source following the instructions in the README. I'm using GNOME 3.38.0 (using X11 on Debian unstable).

In the Extension manager tool it shows the error:

    No JS module 'tweener' found in search path

**Comment by tallero** [comment]
Tweener is part of GNOME Shell, so by just this message I can't say what's going on. Atm I am using the extension on arch with 3.38 without any perceivable problem.

**Comment by ironchicken** [comment]
Yes, here is the log entry from GNOME Shell:

    Sep 30 15:00:29 xps9343 gnome-shell[10268]: JS ERROR: Extension pixel-saver@deadalnix.me: ImportError: No JS module 'tweener' found in search path
        @/home/user/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/app_menu.js:6:17
        @/home/user/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/extension.js:50:17
        _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:420:13
        loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:345:27
        _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18
        collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
        _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19
        _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18
        _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18
        init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
        _initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
        start@resource:///org/gnome/shell/ui/main.js:159:5
        @<main>:1:47

**Comment by ironchicken** [comment]
So I can't find `tweener.js` anywhere on my computer. From this merge, it looks like it may have been removed? https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1200/diffs

I'm also checking if it's actually in Debian at all: https://packages.debian.org/search?suite=sid&arch=any&mode=path&searchon=contents&keywords=tweener.js, but the results are a bit confusing. The two likely candidates are `gnome-js-common` (but this doesn't actually exist in unstable) and `gnome-shell-common` (but this doesn't actually contain `tweener.js`).

**Comment by tallero** [comment]
I have commited a fix some hours ago. Can you check if it is working now?

**Comment by ironchicken** [comment]
Yes, this now works for me with latest `master`. Thanks!
