### ISSUE TITLE
No longer works in 3.38.0

### ISSUE THREAD

**Issue by rayzorben** [pixel-saver/pixel-saver#216]
Getting error and not loading in most recent gnome version

**Comment by grandtoubab** [comment]
idem
Debian 11 Bullseye gnome-shell 3.38

![Capture d’écran du 2020-10-08 18-50-59](https://user-images.githubusercontent.com/30148403/95489651-71452280-0997-11eb-9910-aba295fe8c32.png)

**Comment by tallero** [comment]
It kept working on X.org and the last two commits made it compatible with Wayland again. 

I still have to upload the new version on the extensions website because I heard there were changes on the extension platform I still have to check.

**Comment by tallero** [comment]
I just uploaded the new release on extensions website, waiting for [review](https://extensions.gnome.org/review/19816). Meanwhile you can install the extension from this repo.

**Comment by grandtoubab** [comment]
Monday october 12, still not available for 3.38
![Capture d’écran de 2020-10-12 09-30-02](https://user-images.githubusercontent.com/30148403/95717857-e487b680-0c6d-11eb-9251-3796a04904af.png)

**Comment by tallero** [comment]
@grandtoubab You don't know how extensions on the website get upgraded, am I right? Basically there's a [queue](https://extensions.gnome.org/review/).
