### ISSUE TITLE
not available for 3.38

### ISSUE THREAD

**Issue by grandtoubab** [pixel-saver/pixel-saver#217]
Error , not available for 3.38
![Capture d’écran de 2020-10-12 09-30-02](https://user-images.githubusercontent.com/30148403/95717977-10a33780-0c6e-11eb-9db0-f9174b79fec8.png)

**Comment by jubnzv** [comment]
This is somewhat strange, because this extension [supports](https://github.com/pixel-saver/pixel-saver/blob/c5d392861a4474c2bd9827d9f31f99589b5f0f75/pixel-saver%40deadalnix.me/metadata.json#L6) latest versions of gnome-shell.

Probably data on extensions.gnome.org haven't been updated yet?

Anyway, git master version works well with 3.38.

**Comment by grandtoubab** [comment]
Sorry I cant succeed

First  I have to alt + F2 r to be able to enable the extension
second it finished in EROR state

[install-pixel-saver.txt](https://github.com/pixel-saver/pixel-saver/files/5364271/install-pixel-saver.txt)

**Comment by tallero** [comment]
The extension supports latest GNOME version; last upgrade has been submitted last week and we are waiting for publication approval.

Meanwhile, as usual, you could just download it from this website. I see from the log you are indeed getting the source from here, but why are you switching to tag `1.20` (GNOME 3.32)?

**Comment by jubnzv** [comment]
@grandtoubab Not sure, what is going on, but I suggest to take the following steps:
```bash
# Remove the previous version
rm -rf ~/.local/share/gnome-shell/extensions/pixel-saver*

# Install latest version
cd /tmp && git clone https://github.com/pixel-saver/pixel-saver/
cd pixel-saver
cp -r pixel-saver@deadalnix.me ~/.local/share/gnome-shell/extensions/
```

Then restart gnome shell. This is possible with GNOME on X11 using `r` command in `Alt + F2`. If you are using Wayland, restart current session.

And activate extension through `gnome-tweak` GUI or `gnome-extensions` cli.

If you have some problems after this, please send gnome-shell logs from `journalctl $(which gnome-shell)` command.

Hope this helps.

**Comment by grandtoubab** [comment]
Ok with your steps

guy@debian:~$ cd .local/share/gnome-shell/extensions
guy@debian:~/.local/share/gnome-shell/extensions$ ls -alrt
total 28
drwxr-xr-x 2 guy guy 4096 20 mars   2019 nohotcorner@azuri.free.fr
drwxr-xr-x 5 guy guy 4096 27 avril 08:24 lockkeys@vaina.lt
drwxr-xr-x 4 guy guy 4096 27 avril 09:06 openweather-extension@jenslody.de
drwxr-xr-x 4 guy guy 4096  4 oct.  22:02 window-list@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x 5 guy guy 4096  8 oct.  06:59 sensory-perception@HarlemSquirrel.github.io
drwx------ 4 guy guy 4096 12 oct.  11:39 ..
drwxr-xr-x 7 guy guy 4096 12 oct.  12:14 .
guy@debian:~/.local/share/gnome-shell/extensions$ cd /tmp && git clone https://github.com/pixel-saver/pixel-saver/
Clonage dans 'pixel-saver'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 890 (delta 13), reused 18 (delta 7), pack-reused 860
Réception d'objets: 100% (890/890), 1007.46 Kio | 1.08 Mio/s, fait.
Résolution des deltas: 100% (482/482), fait.
guy@debian:/tmp$ cd pixel-saver
guy@debian:/tmp/pixel-saver$ cp -r pixel-saver@deadalnix.me ~/.local/share/gnome-shell/extensions/

Here I restart gnome-shell using alt+F2 r
then continue

guy@debian:/tmp/pixel-saver$ gnome-extensions list
lockkeys@vaina.lt
nohotcorner@azuri.free.fr
openweather-extension@jenslody.de
pixel-saver@deadalnix.me
window-list@gnome-shell-extensions.gcampax.github.com
sensory-perception@HarlemSquirrel.github.io
apps-menu@gnome-shell-extensions.gcampax.github.com
auto-move-windows@gnome-shell-extensions.gcampax.github.com
drive-menu@gnome-shell-extensions.gcampax.github.com
horizontal-workspaces@gnome-shell-extensions.gcampax.github.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com
dash-to-panel@jderose9.github.com
Hide_Activities@shay.shayel.org
guy@debian:/tmp/pixel-saver$ gnome-extensions enable pixel-saver@deadalnix.me
guy@debian:/tmp/pixel-saver$ gnome-extensions show pixel-saver@deadalnix.me
pixel-saver@deadalnix.me
  Nom: Pixel Saver
  Description: Pixel Saver is designed to save pixel by fusing activity bar and title bar in a natural way
  Chemin: /home/guy/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me
  URL: https://github.com/deadalnix/pixel-saver
  État: ENABLED
guy@debian:/tmp/pixel-saver$

**Comment by grandtoubab** [comment]
Meanwhile, as usual, you could just download it from this website. I see from the log you are indeed getting the source from here, but why are you switching to tag 1.20 (GNOME 3.32)?

Because I am not an expert I just follow the steps on main page https://github.com/pixel-saver/pixel-saver

So please fix the page

**Comment by grandtoubab** [comment]
See above

**Comment by tallero** [comment]
@grandtoubab you're right for god's sake
