### ISSUE TITLE
Mismatch beetween Github and gnome-extension

### ISSUE THREAD

**Issue by grandtoubab** [pixel-saver/pixel-saver#218]
Hello 
following https://github.com/pixel-saver/pixel-saver/issues/217 
I can use pixel-saver version 1.24 on gnome-shell 3.38.
 gnome-extensions info pixel-saver@deadalnix.me
pixel-saver@deadalnix.me
  Nom: Pixel Saver
  Description: Pixel Saver is designed to save pixel by fusing activity bar and title bar in a natural way
  Chemin: /home/guy/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me
  URL: https://github.com/deadalnix/pixel-saver
  État: ENABLED

But now the gnome-extension site https://extensions.gnome.org/extension/723/pixel-saver/ propose an update 
But this update goes in error as it pixel-saver 1.23

![Capture d’écran du 2020-10-14 17-04-11](https://user-images.githubusercontent.com/30148403/96008587-0173e380-0e40-11eb-8aa1-74b636090283.png)

Very annoying

**Comment by tallero** [comment]
The `23` on the extensions' website is just a progressive counter indicating a particular review, as far as I know it has no relation with the version number.

![Screenshot from 2020-10-16 12-23-54](https://user-images.githubusercontent.com/7817636/96247567-9561be80-0faa-11eb-8699-9fba0c9dba9a.png)
