### ISSUE TITLE
Gnome 40 support

### ISSUE THREAD

**Issue by gaborbernat** [pixel-saver/pixel-saver#221]
With Fedora rc coming out today using gnome 40 there likely will be an increase of interest in this.

**Comment by tallero** [comment]
Last time I tried it it was working.

**Comment by jhpratt** [comment]
Hi @tallero. As you may or may not have seen on extensions.gnome.org, there is a bug with Fedora 34 & Gnome 40 where the UI outright freezes.

**Comment by tallero** [comment]
It works fine on arch. 
Ihave so ordered some ram memory and I should also buy a new hard drive. Hardware donations welcomed.

**Comment by jhpratt** [comment]
Live disk maybe? Needs minimal hardware (just a flash drive) and would be quick to test.

I'll help if possible, but I've never worked with gnome before.
