### ISSUE TITLE
Only a narrow strip of the changed button is visible on mouse hover

### ISSUE THREAD

**Issue by webmastak** [pixel-saver/pixel-saver#225]
Running Gnome Shell 3.38 in VirtualBox.

On hover, only the narrow horizontal bar of the button works and changes.
Property `hover` doesn't work for buttons in height. 😟 

Gnome Shell 3.38 in VirtualBox:
![1](https://i.imgur.com/TKGf68l.png)
![2](https://i.imgur.com/nCtN5AH.png)

Gnome Shell 3.36 in PC:
![4](https://i.imgur.com/fzA3Icc.jpg)
![5](https://i.imgur.com/A1ckYQt.png)

**Comment by tallero** [comment]
@webmastak does it happen with every theme or just with arc?

**Comment by webmastak** [comment]
This happens with every theme.  
If the height of the top panel is less than the height of the buttons, then they are generally invisible.

**Comment by webmastak** [comment]
You are going to make support for at least Gnome 3.38 ?

Your extension, unlike its counterparts, performed one function and did it well.
The same [unite](https://github.com/hardpixel/unite-shell) with a bunch of settings can conflict with other extensions.

**Comment by tallero** [comment]
>This happens with every theme.
I think you mean pixel saver themes

>My theme is Adapta-Nokto-Eta-Maia, not Arc.
 it's likely that your error depends on your themes/extensions configuration.

 >You are going to make support for at least Gnome 3.38 ?
We had a stable release for gnome 3.38, I have used the extension without problems during that cycle,

**Comment by webmastak** [comment]
> it's likely that your error depends on your themes/extensions configuration.

Yes, I messed up with CSS styles. 😀
The issue can be closed.
