### ISSUE TITLE
Buttons not showing up on VirtualBox, Gnome Shell 3.38, Xorg

### ISSUE THREAD

**Issue by webmastak** [pixel-saver/pixel-saver#226]
Buttons not showing when maximizing application in VirtualBox, Gnome Shell 3.38, Xorg.
If you switch between applications, the buttons appear.

[![](https://img.youtube.com/vi/1fP6Yuquhk8/0.jpg)](https://youtu.be/1fP6Yuquhk8)
[https://youtu.be/1fP6Yuquhk8](https://youtu.be/1fP6Yuquhk8)

![01](https://i.imgur.com/uGSoe6t.png)
![02](https://i.imgur.com/RWh1dXa.png)
![03](https://i.imgur.com/sXbEIyb.png)
![04](https://i.imgur.com/2ifeoUE.png)

For Gnome GTK applications, the buttons appear immediately.

**Comment by tallero** [comment]
Could you try on a vanilla GNOME session?

**Comment by webmastak** [comment]
Unfortunately, when switching to Gnome classi, my custom extensions are disabled. :(
Can't test.

**Comment by tallero** [comment]
I guess it's one of the other extensions

**Comment by webmastak** [comment]
> I guess it's one of the other extensions's fault

No, I tried to disable everything! 
The same [unite](https://github.com/hardpixel/unite-shell) with a bunch of settings can conflict with other extensions.

**Comment by tallero** [comment]
I think the problem lies in how your distributor packaged Shell; maybe some extensions are installed system-wide or they applied some kind of patch, because I didn't have such a problem on vanilla shell.

Also, the things in the log are pretty much fine.

**Comment by webmastak** [comment]
All extensions installed on the system are disabled.
Everything works with gnome 3.36

**Comment by tallero** [comment]
Are you using vanilla Shell or a distro-modded version?

**Comment by webmastak** [comment]
I have  [Manjaro linux](https://manjaro.org/)

**Comment by webmastak** [comment]
Not a lot of persistence and fixed, laid out a fork

**Comment by tallero** [comment]
I didn't get it, does it work for you now? Did you had to commit any change?

**Comment by webmastak** [comment]
> I didn't get it, does it work for you now?
Yes it works.

> Did you had to commit any change? It's not clear because you made a new repo instead of forking the 3.38 tag on this one.
I mixed two extensions - yours and the other person's fork.

**Comment by webmastak** [comment]
Will you correct?

**Comment by tallero** [comment]
Could you rebase the branch such that diffs are shown? Probably you just need to open a merge request :3

**Comment by webmastak** [comment]
So you can see all the differences [here](https://github.com/webmastak/pixel-saver/commit/4a7aa925ccc1469f0fc21ef49e14a7ee87e09dc8)

**Comment by webmastak** [comment]
I do not quite understand. Will you fix it in the master branch? Or should I support the working version on my own?

**Comment by tallero** [comment]
Of course I will merge it if it solves a problem, I left you a comment on your branch btw. It's just a matter of time and testing.

Also, could you give me more info about how to reproduce the bug? i.e. distro version, theme, installed extensions, vm image, etc.

**Comment by webmastak** [comment]
manjaro-gnome-21.0-210315-linux510, Adapta-Nokto-Eta-Maia, one pixel-saver extension

**Comment by webmastak** [comment]
> Of course I will merge it if it solves a problem
You still haven't merged my pull request

**Comment by tallero** [comment]
I didn't have time.

**Comment by tallero** [comment]
I have to look at this again.
