### ISSUE TITLE
Always hide window titlebars

### ISSUE THREAD

**Issue by GooseDeveloper** [pixel-saver/pixel-saver#228]
This extension works great on Ubuntu 20.04! However, I'd like to undecorate _all_ windows, not just maximized ones. Could this be implemented? See also: [Undecorate Window](https://extensions.gnome.org/extension/1208/undecorate)

**Comment by tallero** [comment]
Yes, but it would be a very quirky option.

**Comment by tallero** [comment]
```
xprop -f _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS "0x2, 0x0, 0x0, 0x0, 0x0" # See [1]
```

change the corresponding line in pixel saver source and you have it.
[[1](https://askubuntu.com/questions/928226/xprop-fails-to-undecorate-window)]
