### ISSUE TITLE
[Bug] DPI changes and window controls not re-scaling

### ISSUE THREAD

**Issue by plumlis** [pixel-saver/pixel-saver#233]
My laptop has 4K diskplay and I using it with 200% scaling.
Sometimes I use it with 1080p monitor and set scaling to 100%
After I changed scaling, the windows control buttons ( Max Min Close) won't auto scale to the correct size, It looks sooo big or sooo small.
I have to restart gnome-shell to slove this. (Alt+F2 and type R)
On wayland I have to logout and login again.

**Comment by tallero** [comment]
well luckly one does not change scaling every day, am I right?
