### ISSUE TITLE
Remove buttons

### ISSUE THREAD

**Issue by Paul-Aime** [pixel-saver/pixel-saver#238]
I have no usage of buttons.
It would be great if the extension would be configurable to remove them.
But I do understand that it might be work in progress.

Meanwhile, I found out that you can remove buttons by commenting out the relevant line in `~/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/extension.js`:

```javascript
const ExtensionUtils = imports.misc.extensionUtils;
const Me = ExtensionUtils.getCurrentExtension();
const Decoration = Me.imports.decoration;
// const Buttons = Me.imports.buttons;
const AppMenu = Me.imports.app_menu;
const Main = imports.ui.main

function init(extensionMeta) {
	// Buttons.init(extensionMeta);
	Decoration.init(extensionMeta);
	AppMenu.init(extensionMeta);
}

function enable() {
	// Buttons.enable();
	Decoration.enable();
	AppMenu.enable();
}

function disable() {
	AppMenu.disable();
	Decoration.disable();
	// Buttons.disable();
}
```

**Comment by tallero** [comment]
There is no need for a preference, since the button visibility setting is already taken from desktop settings.

Check `/org/gnome/desktop/wm/preferences/button-layout` from dconf.

**Comment by Paul-Aime** [comment]
Right but actually I still want buttons for non-maximized windows, and no difference is made by `/org/gnome/desktop/wm/preferences/button-layout`.

I can go with commenting out those few lines though.
