### ISSUE TITLE
Incompatible with GNOME version 44

### ISSUE THREAD

**Issue by honzah1** [pixel-saver/pixel-saver#240]
The extension is currently incompatibility with GNOME version 44.

**Comment by tallero** [comment]
Solved by #241

**Comment by wzrdtales** [comment]
broken by #241 . its killing and freezing the shell completely

**Comment by wzrdtales** [comment]
also gtktitlebar is not working in latest gnome just with a  metadata upgrade btw.

https://github.com/velitasali/gtktitlebar/issues/36
