### ISSUE TITLE
titlebar from kate (kde-editor) is not removed

### ISSUE THREAD

**Issue by Thorsten42** [pixel-saver/pixel-saver#31]
Hi,
im using debian jessie with gnome 3.14 and this extension is working great except that it is not working with the editor kate.
If i activate logging i get the following output:

Gjs-Message: JS LOG: [pixel-saver]: Override title Untitled – Kate
Gjs-Message: JS LOG: [pixel-saver]: Could not find XID for window with title Untitled – Kate
Gjs-Message: JS LOG: [pixel-saver]: Could not find XID for window with title Untitled – Kate
Gjs-Message: JS LOG: [pixel-saver]: Could not find XID for window with title Untitled – Kate
Gjs-Message: JS LOG: [pixel-saver]: Finding XID for window Untitled – Kate failed

The error catched at line 47 of the file decoration.js is:
Error: Failed to convert UTF-8 string to JS string: Ungültige Bytefolge in Konvertierungseingabe

other kde applications (i ve tested kile or okular) got their titlebar removed.
Thanks

edit: i ve solved the issue... kde applications need a seperate language pack installed... in my case kde-l10n-de

**Comment by zapashcanon** [comment]
@deadalnix, this can be closed (see the edit).
