### ISSUE TITLE
'appmenu' is not a valid button.

### ISSUE THREAD

**Issue by hjwp** [pixel-saver/pixel-saver#42]
pixel-saver isn't working, and I see this message in syslog whenever I try to start the extension .  Am on Ubuntu Gnome 15.10 beta.

**Comment by deadalnix** [comment]
What version of gnome, what version of pixel saver ?

**Comment by deadalnix** [comment]
Sorry, closed by mistake.

**Comment by hjwp** [comment]
```
gnome-shell --version
GNOME Shell 3.16.3
```

I started with the version on the extensions site, and then updated to the latest master from github...

**Comment by marcohu** [comment]
I can confirm this for both GNOME Shell 3.14.4 and GNOME Shell 3.18.4

**Comment by tallero** [comment]
Closing as per @marcohu comment.
@hjwp can you confirm this still happens?
