### ISSUE TITLE
Nothing happens.

### ISSUE THREAD

**Issue by trusktr** [pixel-saver/pixel-saver#54]
I tried installing like this:

``` sh
git clone https://github.com/deadalnix/pixel-saver.git
cd pixel-saver
git checkout 1.6
cp -r pixel-saver@deadalnix.me ~/.local/share/gnome-shell/extensions
gnome-shell-extension-tool -e pixel-saver@deadalnix.me
```

When I maximize a window, the behavior is the same as before. Tried logging out and back in, but it still didn't work. I'm in Gnome 3.18.2. Does it need to be updated for the latest Gnome?

**Comment by deadalnix** [comment]
IIRC 1.6 only work up to gnome 3.16 . For 3.18 onward, just use master.
