### ISSUE TITLE
pixel-saver fails to boot

### ISSUE THREAD

**Issue by kalter1808** [pixel-saver/pixel-saver#85]
$ gnome-shell -r
Gjs-Message: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
Gjs-Message: JS WARNING: [/home/kalter1808/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js 111]: anonymous function does not always return a value
Gjs-Message: JS LOG: [pixel-saver]: 'appmenu' is not a valid button.
Gjs-Message: JS LOG: Extension "pixel-saver@deadalnix.me" had error: Error: Expected type utf8 for Argument 'path' but got type 'object'
Gjs-Message: JS LOG: loading default theme (Adwaita)

(gnome-shell:32184): Gjs-WARNING **: JS ERROR: could not get remote objects for service org.gnome.SettingsDaemon.Smartcard path /org/gnome/SettingsDaemon/Smartcard: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.Smartcard was not provided by any .service files
_proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:83

I use dantrell-gnome 3.18.5, Gentoo linux
Thanks

**Comment by Nexion** [comment]
I can confirm just the same error:
Error: Expected type utf8 for Argument 'path' but got type 'object'

I'm running gnome-shell-3.20.4 (dantrell-gnome-3.20 overlay) on Funtoo.

**Comment by CapSel** [comment]
In button.js line 174 code after fixes looks like this:
`	// Load the new style
	let cssFile = Gio.file_new_for_path(cssPath);
	St.ThemeContext.get_for_stage(global.stage).get_theme().load_stylesheet(cssPath);
	
`
