### ISSUE TITLE
added installation step on ubuntu

### ISSUE THREAD

**Issue by lgbouma** [pixel-saver/pixel-saver#88]
perhaps obvious first step:
`sudo apt-get install gnome-shell-extensions`

**Comment by deadalnix** [comment]
It is part of the package now ? I got to check that.

**Comment by lgbouma** [comment]
Before installing it I didn't have `gnome-shell-extension-tool` aliased to anything in `gnome-shell-extension-tool -e pixel-saver@deadalnix.me`. After the `gnome-shell-extensions` install, I did.

**Comment by deadalnix** [comment]
It doesn't looks like it is included in that package:

https://packages.debian.org/sid/all/gnome-shell-extensions/filelist

**Comment by lgbouma** [comment]
apt-get installed a different version from the debian package you listed I believe. `apt-cache show gnome-shell-extensions` gives

`Package: gnome-shell-extensions
Priority: optional
Section: universe/gnome
Installed-Size: 1404
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Architecture: all
Version: 3.14.3-0ubuntu1
Depends: dconf-gsettings-backend | gsettings-backend, gnome-shell (>= 3.14), gnome-shell (<< 3.15), gir1.2-atk-1.0, gir1.2-clutter-1.0, gir1.2-gdkpixbuf-2.0, gir1.2-glib-2.0, gir1.2-gmenu-3.0, gir1.2-gtk-3.0, gir1.2-gtop-2.0, gir1.2-mutter-3.0, gir1.2-pango-1.0, gvfs (>= 1.16.0), gnome-session (>= 3.8)
Recommends: gnome-tweak-tool (>= 3.14)
Filename: pool/universe/g/gnome-shell-extensions/gnome-shell-extensions_3.14.3-0ubuntu1_all.deb
[...]
Homepage: https://wiki.gnome.org/GnomeShell/Extensions
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Task: ubuntu-gnome-desktop`

I can't find a listing of then specific contents, but the cited homepage lets you know that the devs expect you to have `gnome-shell-extension-tool` once installing this package, so...

**Comment by tallero** [comment]
`gnome-shell-extension-tool` is in `gnome-shell` package.
