### ISSUE TITLE
undefined has no properties

### ISSUE THREAD

**Issue by pipedream** [pixel-saver/pixel-saver#96]
Hi

Great extension, thanks!

How can I debug an "undefined has no properties" error?
It is not clear which object is undefined when I look in "looking glass". Where can I trace logs more closely?

I do not get this on all my computers -- could be another incompatible extension, or packaged install in /usr versus user install in .local. I am runnign Debian testing and Gnome-shell 3.22.2

Regards,
Jan

**Comment by pipedream** [comment]
(1) Some apps (nautilus, gnome-tweak-tool, dconf-editor) use 
org.gnome.desktop.wm.preferences/button-layout. If it contains no ":" to indidicate whether min-max-close buttons are on the left or right, then pixelsaver throws a orders[1] is undefined (which I think is the same undefined has no properties error). Adding a : to this fixed my pixelsaver for (2) below, bizarrely. These apps still do not (and I think never did) work with pixelsaver when maximized. The title bar was/is below the panel.

furthermore, gnome-tweak-tool > windows > Maximize on/off and Minimize on/off only appends to the above setting. Never removes. You get more and more minimizes by toggling that.

(2) Some apps (firefox, vlc, transmission-gtk) use org.gnome.shell.extensions.classic-overrides.button-layout (description: overrides above key, but does not). gnome-tweak-tool does not edit this.

Both above keys have close,minimize,maximize; as default (which might be our custom distro setting, will check -- highvoltage?)

Note you can set things like close,miminize,maximize:maximize,minimize,close and have things on both sides.

**Comment by deadalnix** [comment]
So yes, if you have no : in there I'm not sure this field is valid.

For apps not working, there are 2 possibilities. If you use wayland, the gtk3 apps won't work. i'm looking for a solution but it isn't usre there is one at all because of the way wayland works. Otherwise, it won't work with apps with a ton of stuff in the status bar, as it is the case for many gone apps, as removing it would make the app useless.

**Comment by tallero** [comment]
You can try with 
```
journalctl /usr/bin/gnome-shell -f -o cat
```

[Source](https://stackoverflow.com/questions/8425616/how-to-test-debug-gnome-shell-extensions-is-there-any-tool-for-that)
